### ISSUE TITLE
Turn off for CSS files

### ISSUE THREAD

**Issue by dstout** [attenzione/SublimeLinter-scss-lint#31] opened 2015-09-04 15:58 UTC
I have SublimeLinter-csslint installed, but scss-lint is overriding it. The SCSS linter has a lot of advice that's not relevant to CSS files, such as using variables for constants. Is there a configuration option for turning off scss-lint just for CSS files? Thanks.

**Comment by attenzione** [comment] 2015-09-09 12:40
duplicate of #22

**Closed by attenzione** 2015-09-09 12:40 UTC
